apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: datasources.grafana.org
  finalizers:
    - finalizer.datasource.grafana.org
spec:
  group: grafana.org
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: datasources
    singular: datasource
    kind: DataSource
    shortNames:
    - ds
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            name:
              type: string
            type:
              type: string
            access:
              type: string
            url:
              type: string
            password:
              type: stringA
            user:
              type: string
            database:
              type: string
            basicAuth:
              type: boolean
            basicAuthUser:
              type: string
            basicAuthPassword:
              type: string
            isDefault:
              type: boolean
            jsonData:
              type: object
          required:
            - name
            - type
