apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: folders.grafana.org
  finalizers:
    - finalizer.datasource.grafana.org
spec:
  group: grafana.org
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: folders
    singular: folders
    kind: Folder
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            uid:
              type: string
              title: Optional unique identifier.
            title:
              type: string
              title: The title of the folder.
          required:
            - title
